import { Kegiatan } from "./types";

export const mockData: Kegiatan[] = [
  {
    id: "1",
    tahapan: "Perencanaan",
    uraianKegiatan: "Penyusunan DED (Detail Engineering Design)",
    output: "Dokumen DED lengkap",
    tanggalMulai: "2024-01-15",
    tanggalSelesai: "2024-03-15",
    statusProgres: "Selesai",
    persentaseProgres: 100,
    peranPenyedia: "Konsultan Perencana",
    pic: "Ir. Ahmad Fauzi",
    peranBPSKabupaten: "Review & persetujuan",
    peranBPSProvinsi: "Konsultasi teknis",
    peranPusat: "Persetujuan anggaran",
    linkBuktiDukung: "https://drive.google.com/example1",
    keterangan: "DED telah disetujui dan difinalisasi",
    tindakLanjut: "-",
    nomorKontrak: "KTR/PLAN/001/2024",
    tanggalUpdateTerakhir: "2024-03-15",
  },
  {
    id: "2",
    tahapan: "Perencanaan",
    uraianKegiatan: "Penyusunan RAB (Rencana Anggaran Biaya)",
    output: "Dokumen RAB final",
    tanggalMulai: "2024-02-01",
    tanggalSelesai: "2024-04-01",
    statusProgres: "Selesai",
    persentaseProgres: 100,
    peranPenyedia: "Konsultan Perencana",
    pic: "Dra. Siti Nurhaliza",
    peranBPSKabupaten: "Verifikasi volume & harga",
    peranBPSProvinsi: "Review anggaran",
    peranPusat: "Alokasi anggaran DIPA",
    linkBuktiDukung: "https://drive.google.com/example2",
    keterangan: "RAB telah disesuaikan dengan standar biaya",
    tindakLanjut: "-",
    nomorKontrak: "KTR/PLAN/002/2024",
    tanggalUpdateTerakhir: "2024-04-01",
  },
  {
    id: "3",
    tahapan: "Perencanaan",
    uraianKegiatan: "Pengurusan IMB / PBG",
    output: "Dokumen IMB/PBG terbit",
    tanggalMulai: "2024-03-01",
    tanggalSelesai: "2024-05-30",
    statusProgres: "Proses",
    persentaseProgres: 75,
    peranPenyedia: "Konsultan Perencana",
    pic: "Ir. Ahmad Fauzi",
    peranBPSKabupaten: "Koordinasi Pemda",
    peranBPSProvinsi: "Fasilitasi",
    peranPusat: "-",
    linkBuktiDukung: "https://drive.google.com/example3",
    keterangan: "Menunggu verifikasi Dinas PUPR",
    tindakLanjut: "Follow up ke Dinas PUPR minggu depan",
    nomorKontrak: "KTR/PLAN/003/2024",
    tanggalUpdateTerakhir: "2024-05-20",
  },
  {
    id: "4",
    tahapan: "Pelaksanaan",
    uraianKegiatan: "Pekerjaan Struktur Fondasi",
    output: "Fondasi gedung selesai",
    tanggalMulai: "2024-06-01",
    tanggalSelesai: "2024-08-30",
    statusProgres: "Proses",
    persentaseProgres: 60,
    peranPenyedia: "Kontraktor Pelaksana",
    pic: "H. Dedi Mulyadi, ST",
    peranBPSKabupaten: "Monitoring harian",
    peranBPSProvinsi: "Monitoring berkala",
    peranPusat: "Evaluasi progress",
    linkBuktiDukung: "https://drive.google.com/example4",
    keterangan: "Terkendala cuaca hujan minggu ke-3",
    tindakLanjut: "Percepatan pekerjaan saat cuaca cerah",
    nomorKontrak: "KTR/EXE/001/2024",
    tanggalUpdateTerakhir: "2024-07-25",
  },
  {
    id: "5",
    tahapan: "Pelaksanaan",
    uraianKegiatan: "Pekerjaan Struktur Kolom & Balok Lt.1",
    output: "Struktur kolom & balok lantai 1",
    tanggalMulai: "2024-08-01",
    tanggalSelesai: "2024-10-30",
    statusProgres: "Belum",
    persentaseProgres: 0,
    peranPenyedia: "Kontraktor Pelaksana",
    pic: "H. Dedi Mulyadi, ST",
    peranBPSKabupaten: "Monitoring harian",
    peranBPSProvinsi: "Monitoring berkala",
    peranPusat: "-",
    linkBuktiDukung: "",
    keterangan: "Menunggu penyelesaian fondasi",
    tindakLanjut: "Persiapan material kolom",
    nomorKontrak: "KTR/EXE/001/2024",
    tanggalUpdateTerakhir: "2024-07-25",
  },
  {
    id: "6",
    tahapan: "Pelaksanaan",
    uraianKegiatan: "Pekerjaan Atap & Rangka",
    output: "Atap gedung terpasang",
    tanggalMulai: "2024-11-01",
    tanggalSelesai: "2025-01-15",
    statusProgres: "Belum",
    persentaseProgres: 0,
    peranPenyedia: "Kontraktor Pelaksana",
    pic: "Andi Saputra, ST",
    peranBPSKabupaten: "Monitoring",
    peranBPSProvinsi: "-",
    peranPusat: "-",
    linkBuktiDukung: "",
    keterangan: "-",
    tindakLanjut: "-",
    nomorKontrak: "KTR/EXE/001/2024",
    tanggalUpdateTerakhir: "2024-07-25",
  },
  {
    id: "7",
    tahapan: "Pelaksanaan",
    uraianKegiatan: "Pekerjaan Finishing & MEP",
    output: "Gedung siap fungsi",
    tanggalMulai: "2025-01-16",
    tanggalSelesai: "2025-04-30",
    statusProgres: "Belum",
    persentaseProgres: 0,
    peranPenyedia: "Kontraktor Pelaksana",
    pic: "Andi Saputra, ST",
    peranBPSKabupaten: "Quality check",
    peranBPSProvinsi: "Inspeksi akhir",
    peranPusat: "Serah terima",
    linkBuktiDukung: "",
    keterangan: "-",
    tindakLanjut: "-",
    nomorKontrak: "KTR/EXE/001/2024",
    tanggalUpdateTerakhir: "2024-07-25",
  },
  {
    id: "8",
    tahapan: "Pengawasan",
    uraianKegiatan: "Pengawasan Berkala Tahap Fondasi",
    output: "Laporan pengawasan fondasi",
    tanggalMulai: "2024-06-01",
    tanggalSelesai: "2024-08-30",
    statusProgres: "Proses",
    persentaseProgres: 55,
    peranPenyedia: "Konsultan Pengawas",
    pic: "Ir. Bambang Wijaya",
    peranBPSKabupaten: "Koordinasi lapangan",
    peranBPSProvinsi: "Review laporan",
    peranPusat: "-",
    linkBuktiDukung: "https://drive.google.com/example8",
    keterangan: "Pengawasan berjalan sesuai jadwal",
    tindakLanjut: "Lanjut pengawasan mingguan",
    nomorKontrak: "KTR/SUP/001/2024",
    tanggalUpdateTerakhir: "2024-07-20",
  },
  {
    id: "9",
    tahapan: "Pengawasan",
    uraianKegiatan: "Review Kualitas Material",
    output: "Sertifikat uji material",
    tanggalMulai: "2024-06-15",
    tanggalSelesai: "2025-04-30",
    statusProgres: "Proses",
    persentaseProgres: 30,
    peranPenyedia: "Konsultan Pengawas",
    pic: "Ir. Bambang Wijaya",
    peranBPSKabupaten: "Sampling material",
    peranBPSProvinsi: "-",
    peranPusat: "-",
    linkBuktiDukung: "https://drive.google.com/example9",
    keterangan: "Beton & besi sudah lolos uji",
    tindakLanjut: "Uji material tahap selanjutnya",
    nomorKontrak: "KTR/SUP/001/2024",
    tanggalUpdateTerakhir: "2024-07-18",
  },
  {
    id: "10",
    tahapan: "Pelaksanaan",
    uraianKegiatan: "Mobilisasi Alat & Material",
    output: "Alat & material tersedia di lokasi",
    tanggalMulai: "2024-05-15",
    tanggalSelesai: "2024-06-10",
    statusProgres: "Tertunda",
    persentaseProgres: 40,
    peranPenyedia: "Kontraktor Pelaksana",
    pic: "H. Dedi Mulyadi, ST",
    peranBPSKabupaten: "Verifikasi material",
    peranBPSProvinsi: "-",
    peranPusat: "-",
    linkBuktiDukung: "https://drive.google.com/example10",
    keterangan: "Terkendala akses jalan ke lokasi proyek",
    tindakLanjut: "Koordinasi dengan Dinas PU untuk perbaikan akses",
    nomorKontrak: "KTR/EXE/001/2024",
    tanggalUpdateTerakhir: "2024-06-05",
  },
];
