// This file is automatically generated. Do not edit it directly.
import { createClient } from '@supabase/supabase-js';
import type { Database } from './types';

const SUPABASE_URL = "https://usgjbpyzhoiykbooxzjh.supabase.co";
const SUPABASE_PUBLISHABLE_KEY = "eyJhbGciOiJIUzI1NiIsInR5cCI6IkpXVCJ9.eyJpc3MiOiJzdXBhYmFzZSIsInJlZiI6InVzZ2picHl6aG9peWtib294empoIiwicm9sZSI6ImFub24iLCJpYXQiOjE3NzQ4NzA3MDksImV4cCI6MjA5MDQ0NjcwOX0.X5TxGlp2eIvmM7CgWLGwrc9lJ4gBtjEhM_inOrcUtOg";

// Import the supabase client like this:
// import { supabase } from "@/integrations/supabase/client";

export const supabase = createClient<Database>(SUPABASE_URL, SUPABASE_PUBLISHABLE_KEY, {
  auth: {
    storage: localStorage,
    persistSession: true,
    autoRefreshToken: true,
  }
});